language: php

php:
  - 5.6
  - 7.4

env:
  matrix:
    - DB=mysql DB_DSN='mysql://root@127.0.0.1/cakephp_test'
  global:
    - DEFAULT=1

services:
  - postgresql
  - mysql

matrix:
  fast_finish: true

  include:
    - php: 7.1
      env: DB=pgsql DB_DSN='postgres://postgres@127.0.0.1/cakephp_test'

    - php: 5.6
      env: PREFER_LOWEST=1

    - php: 7.3
      env: CHECKS=1 DEFAULT=0

    - php: 7.3
      env: CODECOVERAGE=1 DEFAULT=0 DB=mysql DB_DSN='mysql://root@127.0.0.1/cakephp_test'

before_install:
  - if [[ $CODECOVERAGE != 1 && ${TRAVIS_PHP_VERSION} != "7.4" ]]; then phpenv config-rm xdebug.ini; fi

before_script:
  - if [[ ${TRAVIS_PHP_VERSION} == "5.6" ]]; then composer require --dev phpunit/phpunit-mock-objects:^3.4.4; fi

  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-source --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction ; fi

  - if [[ $DB == 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;' ; fi
  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit ; fi

  - if [[ $CHECKS == 1 ]]; then composer phpstan-setup && composer phpstan ; fi
  - if [[ $CHECKS == 1 ]]; then composer cs-check ; fi

  - if [[ $CODECOVERAGE == 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml ; fi
  - if [[ $CODECOVERAGE == 1 ]]; then wget -O codecov.sh https://codecov.io/bash ; fi
  - if [[ $CODECOVERAGE == 1 ]]; then bash codecov.sh ; fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
